KODIK_TOKEN = None
SHIKIMORI_MIRROR = "shikimori.io"  # ← изменено
APP_SECRET_KEY = "TvoyaMamashaSosetUKrasnoluda"
DEBUG = True  # ← включено для отладки
SAVE_DATA = True
USE_SAVED_DATA = True
SAVED_DATA_FILE = "cache.json"
SAVING_PERIOD = 5
CACHE_LIFE_TIME = 3
ALLOW_WATCH_TOGETHER = True
REMOVE_TIME = 5
ALLOW_NSFW = True
IMAGE_NOT_FOUND = "/resources/no-image.png"
IMAGE_AGE_RESTRICTED = "/resources/age-restricted.png"
FAVICON_PATH = "resources/favicon.ico"
HOST = '0.0.0.0'
PORT = 5000
USE_LXML = True